matchbox_http_endpoint = "http://matchbox.tsuzu.dev:28080"
matchbox_rpc_endpoint = "matchbox.tsuzu.dev:28081"
ssh_authorized_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1SbtZX9JodwxhazqRkBOTzN2AtyeFlgOnO+bXY+Rm/eabX/s9oqcOITZabnFbn0EmPOXuMCzyDRdTJqA1fJr8eGi4bDZTTjwji9UgxrwPeJURgKus3u1O2P9rT0fpRMt82E9rrkbQWjQee6c0KII0QQO5mmblKSfl8UP7QqzIaUpCfFx/tjty7at+qrPuYo5ulI8eQ6RNXYzTLVgAtdFWZWz3sNLSkHAGyciOs3vzqvXlskGfCl6XRwZYiPG/nv9fRRdOaIIR/ghWHbjOsnkqx8STKmDCDTdQN1bSc0IPZPdoMRRHDHYNhrAIvVpLWoha/crICLwELhiLxe5d4BdX"
